[package]
name = "acqua_arrugginita"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
rand = "0.8.5"
thiserror = "1.0.63"

[dependencies.sdl2]
version = "0.37.0"
default-features = false


